spring:
  application:
    name: aimiddleware
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 6
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false  # Inserts data after hibernate table creation. Useful for DEV purposes
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false