spring:
  application:
    name: aimiddleware
  datasource:
    # MySQL mode is only necesary for INSERT IGNORE of the data.sql script
    url: jdbc:h2:~/aimiddleware/mydb;MODE=MySQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false  # Inserts data after hibernate table creation. Useful for DEV purposes
  sql.init:
    mode: always
    schema-locations: classpath*:schema.sql
    data-locations: classpath*:data.sql
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  endpoint.health.enabled: true
  endpoints.web.exposure.include: health, metrics