spring:
  application:
    name: aimiddleware
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true  # Inserts data after hibernate table creation. Useful for DEV purposes
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false