spring:
  application:
    name: aimiddleware
  datasource:
    url: jdbc:h2:~/aimiddleware/mydb;\DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;FILE_LOCK=SOCKET;WRITE_DELAY=0
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: db/changelog/changelog.h2.sql
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
management:
  endpoint:
    health.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: health, info, metrics, prometheus
vaadin:
  devmode.devTools.enabled: false
# RestClient logging
#logging.level.org.apache.hc.client5.http: DEBUG
